# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android -r features/step_definitions


ios: PLATFORM=ios APP_BUNDLE_PATH=apps/WordPress.app  -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages

